### ISSUE TITLE
Cart Access Denied: Error Message for Unregistered Users

### ISSUE THREAD

**Issue by smarikachaudhary** [SwasthaniStha/Farmish#12]
When an unregistered user tries to access the cart, an error message is shown.
![pranjalsIssue](https://github.com/SwasthaniStha/Farmish/assets/119168456/a01e7733-02c3-4aa1-90e3-b354f544c0a4)

**Comment by pranjalipudasaini** [comment]
This issue was likely caused by the path not matching any path present in urls.py. This issue has been solved by adding a login url in settings.py file.
![image](https://github.com/SwasthaniStha/Farmish/assets/119116985/6153287d-74fa-4086-9b63-dd6a83f8d0ac)

**Comment by smarikachaudhary** [comment]
Great!
