### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by smarikachaudhary** [SwasthaniStha/Farmish#15]
The UI design here is not similar with the other pages i.e. footer. 
![unnamed](https://github.com/SwasthaniStha/Farmish/assets/119168456/2a8b6eb8-d69a-4d8b-b588-5930938100a6)

**Comment by pranjalipudasaini** [comment]
This issue has been solved.
![image](https://github.com/SwasthaniStha/Farmish/assets/119116985/a216a850-71d1-453b-86d6-89c0af30d40b)

**Comment by smarikachaudhary** [comment]
Great Job!
