### ISSUE TITLE
Logo in Admin Dashboard

### ISSUE THREAD

**Issue by smarikachaudhary** [SwasthaniStha/Farmish#16]
While clicking on the logo of admin dashboard, it redirects to consumer dashboard! It should redirect to the same dashboard.

**Comment by pranjalipudasaini** [comment]
The issue has been solved by adding the URL to admin dashboard in the logo.
![image](https://github.com/SwasthaniStha/Farmish/assets/119116985/567e72f1-08fa-4cc9-b90d-d6323a0770a0)
