### ISSUE TITLE
Imports and app not register issue in Individual farmer

### ISSUE THREAD

**Issue by smarikachaudhary** [SwasthaniStha/Farmish#19]
![astika](https://github.com/SwasthaniStha/Farmish/assets/119168456/e5b66926-8b90-4359-b709-44e13d9b6014)

**Comment by Astika-Poudel** [comment]
![image](https://github.com/SwasthaniStha/Farmish/assets/118663681/1f6eed8c-b7ed-46bb-99c3-2dc4d1fb48d6)
Done!
