### ISSUE TITLE
Invalid error in Order Status Update

### ISSUE THREAD

**Issue by smarikachaudhary** [SwasthaniStha/Farmish#22]
Invalid error in Order Status Update
![image](https://github.com/SwasthaniStha/Farmish/assets/119168456/0aff41c0-24c7-4e0d-8580-449831b65792)

**Comment by Astika-Poudel** [comment]
Done
![image](https://github.com/SwasthaniStha/Farmish/assets/118663681/5fd6a5c6-40d6-4770-8532-62edd40893c9)
![image](https://github.com/SwasthaniStha/Farmish/assets/118663681/34d64ca5-95da-4eca-83d7-bdd2a34336a6)
