### ISSUE TITLE
Quantity and Price Update error

### ISSUE THREAD

**Issue by smarikachaudhary** [SwasthaniStha/Farmish#23]
The price does not get updated according to the increase in quantity. 
![image](https://github.com/SwasthaniStha/Farmish/assets/119168456/3e2310ac-7e73-4c1b-b884-8db2408fef8c)

**Comment by Astika-Poudel** [comment]
done
![image](https://github.com/SwasthaniStha/Farmish/assets/118663681/52cd1efe-03a2-4111-b2c5-653c5e489499)
