### ISSUE TITLE
Missing Contact Form

### ISSUE THREAD

**Issue by smarikachaudhary** [SwasthaniStha/Farmish#36]
Failed to display Contact us form in the consumer dashboard.
![image](https://github.com/SwasthaniStha/Farmish/assets/119168456/028c559a-2f4e-4350-95a4-2dd6e2e549c2)

**Comment by pranjalipudasaini** [comment]
The issue has been solved.
![image](https://github.com/SwasthaniStha/Farmish/assets/119116985/b6871e57-ea5e-4041-8fb7-80f487412560)
